# models/ — trained ML model files (.pkl) go here
# isolation_forest.pkl   — IsolationForest for gap detection
# grievance_pipeline.pkl — TF-IDF + RandomForest for grievance classification
#
# These are generated by running:
#   python scripts/train_models.py
#
# They are gitignored (binary files).
